// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnvZS2a6bvsVarN30EN6q36BFC5T9jGoE',
    appId: '1:760107819088:web:1e790893444fbf7d0b3155',
    messagingSenderId: '760107819088',
    projectId: 'modul3-a3a9c',
    authDomain: 'modul3-a3a9c.firebaseapp.com',
    storageBucket: 'modul3-a3a9c.appspot.com',
    measurementId: 'G-DT14T9K7H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHBO7-birU1mm5GCECSlgmg6J1Q1HIK28',
    appId: '1:760107819088:android:d6a2c85f9ec941f20b3155',
    messagingSenderId: '760107819088',
    projectId: 'modul3-a3a9c',
    storageBucket: 'modul3-a3a9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkyPBv3ljZ9-1p9kCAXlm5KQ1L6DEwxco',
    appId: '1:760107819088:ios:f92cceaf0ce96c0e0b3155',
    messagingSenderId: '760107819088',
    projectId: 'modul3-a3a9c',
    storageBucket: 'modul3-a3a9c.appspot.com',
    iosBundleId: 'com.modul3auth.modul3auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkyPBv3ljZ9-1p9kCAXlm5KQ1L6DEwxco',
    appId: '1:760107819088:ios:f92cceaf0ce96c0e0b3155',
    messagingSenderId: '760107819088',
    projectId: 'modul3-a3a9c',
    storageBucket: 'modul3-a3a9c.appspot.com',
    iosBundleId: 'com.modul3auth.modul3auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnvZS2a6bvsVarN30EN6q36BFC5T9jGoE',
    appId: '1:760107819088:web:3dd4cd9ae605b0600b3155',
    messagingSenderId: '760107819088',
    projectId: 'modul3-a3a9c',
    authDomain: 'modul3-a3a9c.firebaseapp.com',
    storageBucket: 'modul3-a3a9c.appspot.com',
    measurementId: 'G-M0ZDV2QWGK',
  );
}
